### ISSUE TITLE
모달의 multi-step 수정 (협의 후)

### ISSUE THREAD

**Issue by 0214kbs** [gamemuncheol/gamemuncheol-frontend#39]
### [목표]
모달의 multi-step 기능을 어떻게 처리할 지 회의가 필요할 것 같습니다. (discord)

### [변경될 사항]

- [ ]  이후 작성 예정

### [참고 사항(동작 화면 등)]
isPage, pageN, pageM : 모달의 header에 보여지는 N/M ( 디자인 요소 )
multi-step 기능 : 회원가입 시(약관동의-nickname) , 등록 모달(1/5 ~5/5)

https://github.com/gamemuncheol/gamemuncheol-frontend/pull/35#discussion_r1645250796

**Comment by 0-Chan** [comment]
넵!! 일단 어떤 방식이 옳은지 정답이 없는 문제일 수 있으니까요.
말씀 주신 것 처럼 discord로 이야기 나눠보는게 좋을 것 같습니다.

**Comment by 0-Chan** [comment]
그간 진척 사항에 대해서 좀 정리해서 말씀 드리겠습니다!!

1. `React.createPortal` 적용
<img width="795" alt="SCR-20240725-puhz" src="https://github.com/user-attachments/assets/bc5fec8d-cbed-419a-9ee7-80c0819d1c4e">

기존은 모달을 사용하는 DOM 계층 구조 하위에 <Modal /> 컴포넌트가 들어가는 형식 이었는데요.
createPortal을 사용하는 `<Portal />` 컴포넌트로 `<Modal />`을 감싸서 가장 상위로(body 태그 옆에) 올리는 작업을 했습니다.

혹시 제가 설명 드린게 잘 이해가 안 가셨다면 말씀주세요..!

**Comment by 0-Chan** [comment]
2. sub component 도입 여부 논의

이슈가 만들어진 이유인 multi-step 모달의 단계를 표시하기 위해서 pageN/M을 props로 넘기는 코드를 짜신 것을 보고 제가 분리하는건 어떨까 제안을 드렸었는데요.

이게 생각해보니까 **디자인이 큰 변경점이 없을거라고 하면 그대로 유지해도 되겠다**라는 생각이 들었습니다.

그럼 만약 props로 안넘기면 어떤 방식을 취해야 하냐고 했을 때 sub component 방법을 쓰는 곳이 있었는데요.

예를 들면 `<Modal />` 컴포넌트 외에 `<ModalHeader />`, `<ModalFooter />` 이런 식으로 모달을 분리하여 작성하는 방법을 뜻하는 것 같더라구요.

그래서 지금 방식을 그대로 유지할지(props 방식) 아니면 바꿀지(sub component 방식)를 논의 드리고 싶습니다.
