### ISSUE TITLE
피그마 디자인에 추가될 이슈 정리

### ISSUE THREAD

**Issue by 0-Chan** [gamemuncheol/gamemuncheol-frontend#42]
### [변경될 사항]

- [x] Solution1
- [ ]

**Comment by 0214kbs** [comment]
홈>등록05(완료/등록본인) 부분
![image](https://github.com/gamemuncheol/gamemuncheol-frontend/assets/87002218/e0342a95-c4d8-472d-bd1f-e7cba2fcc584)
1. 버튼들의 padding 값이 일정하지 않아서, 통일성이 없습니다.
2. 수정 버튼의 위치가 어색한 것 같습니다.
3. 높이도 제각각이라 어색한 부분이 더 있는 것 같습니다
4. 취소 등록 버튼 사이의 간격이 너무 먼 것 같습니다.
버튼들끼리의 간격도 통일되면 좋을 것 같습니다.

**Comment by rookedsysc** [comment]
홈>등록05(완료/등록본인) 부분
<img width="154" alt="image" src="https://github.com/gamemuncheol/gamemuncheol-frontend/assets/67862775/f7f0220d-30d2-49ac-ab36-244424ec711e">

1. 좋아요/팔로우 버튼 삭제 필요

**Comment by 0214kbs** [comment]
홈>등록05(완료/등록본인) 부분
### 댓글 부분
![image](https://github.com/gamemuncheol/gamemuncheol-frontend/assets/87002218/5f665c5e-4578-403e-b4c3-73acf49d4e0b)
1. 답글 버튼이 1개만 나와야 할 것 같습니다. ( 대댓글까지만 달도록 되어있음)
2. 투표 안 하고 댓글 쓰는 사람은 어떻게 표시해야할 지 나와있지 않습니다!
3. 댓글 수정/삭제 버튼이 없습니다.


### 투표하는 버튼 
![image](https://github.com/gamemuncheol/gamemuncheol-frontend/assets/87002218/3c69d013-6acf-4802-9750-4b547296ed06)
이부분이 투표하는 버튼이라고 가정하고 말씀 드리자면, 투표 여부에 따라 색깔이 연하게 바뀌면 좋을 것 같습니다. (투표 여부, 어느 팀에 투표했는지가 드러나지 않습니다!)  

### 필터 버튼
아래 버튼들의 설명이 모호한 것 같습니다.. 
![image](https://github.com/gamemuncheol/gamemuncheol-frontend/assets/87002218/2611447c-3041-450f-baeb-8cc9fff6eff7)
1. 팀 버튼으로 댓글 필터링을 하고, 위에 '팀필터', '댓글필터'는 필요없는 것 같습니다. 
2. 두개 너비가 동일하면 좋을 것 같습니다.

**Comment by 0214kbs** [comment]
1. 등록 모달의 위치를 모두 가운데에 두었으면 합니다. 
2. 아래 텍스트 부분은 이미지로 되어있습니다. 
![image](https://github.com/gamemuncheol/gamemuncheol-frontend/assets/87002218/eae12bfc-1bf1-4be3-b859-a795496f7d6a)

**Comment by 0214kbs** [comment]
### 이용약관 동의, 닉네임 입력 (회원가입 부분)
모달의 통일성을 위해,  
1. 취소버튼과 확인 버튼이 바뀌었으면 합니다.
2. 취소,확인 대신 (취소, 다음) (이전, 다음) 과 같은 단어는 어떤가요
3. X 버튼 옆에 1/2, 2/2 가 있으면 좋을 것 같습니다. 
![image](https://github.com/gamemuncheol/gamemuncheol-frontend/assets/87002218/cbbc0dd0-366a-4ed8-9b79-34deb9f699ae)

**Comment by JamesDean0601** [comment]
### 개인정보처리방침 부분

마케팅 수신 동의는 빼야하지 않나요?
<img width="245" alt="스크린샷 2024-07-07 오후 9 47 49" src="https://github.com/gamemuncheol/gamemuncheol-frontend/assets/154765974/48accb76-1c2d-4b53-9664-caa84efa39d0">

**Comment by JamesDean0601** [comment]
### 모바일 권한 부분

카메라 권한은 필요 없을 것 같습니다.
<img width="207" alt="스크린샷 2024-07-07 오후 9 45 38" src="https://github.com/gamemuncheol/gamemuncheol-frontend/assets/154765974/deac24b3-2d7c-4aad-be42-32724d828a63">

**Comment by JamesDean0601** [comment]
### 바텀 네비 부분

롤문톡이랑 등록은 빠져야 합니다.
![Uploading 스크린샷 2024-07-07 오후 9.47.25.png…]()

**Comment by JamesDean0601** [comment]
### 바텀 네비 부분

롤문톡이랑 등록은 빠져야 합니다.
<img width="371" alt="스크린샷 2024-07-07 오후 9 47 25" src="https://github.com/gamemuncheol/gamemuncheol-frontend/assets/154765974/7ced91cc-f520-431e-b6f3-e07397f89d97">

**Comment by JamesDean0601** [comment]
### 썸네일 업로드 부분

저희 여기 사진 추가는 빠져야 합니다.
<img width="187" alt="스크린샷 2024-07-07 오후 9 46 43" src="https://github.com/gamemuncheol/gamemuncheol-frontend/assets/154765974/8ed7c00d-6296-436f-8da9-8ca8dfdd5950">

**Comment by 0-Chan** [comment]
웹 내 반응형을 고려할 부분이 크게 2가지 정도 있는 것 같습니다.

1. 사이드바에서 자동적으로 메뉴 확장이 되는 기준
2. 홈 화면에서 영상이 한 줄에 몇 개씩 보여야 하는지

![image](https://github.com/user-attachments/assets/e2721bd4-2baa-49d9-9c67-04c0e846f2d3)
