### ISSUE TITLE
회원가입 모달 수정

### ISSUE THREAD

**Issue by 0214kbs** [gamemuncheol/gamemuncheol-frontend#50]
### [목표]
회원가입 모달

### [변경될 사항]

- [x] progress bar
- [x] 회원가입 모달에 적용
- [x] 마켓팅 수신동의 제거
- [x] 필수 동의 전부 선택하지 않아도 다음으로 넘어가지는 문제
- [x] 동의 내용 부분 constants 폴더로 분리
- [ ] 개인정보동의 + 닉네임 합치기 (회원가입 모달의 1/2, 2/2 step이므로 한 파일에 관리하는 방향)

**Comment by 0-Chan** [comment]
지금 `@common`에 있는 `<Progress />` 컴포넌트는 급조된 거라 바꾸고 싶으시다면 얼마든지 바꾸셔도 좋아요!

**Comment by 0-Chan** [comment]
근데 만약 그대로 쓰신다고 하면, `<Modal.Header>` 사이에 children 으로 넣어주시면 되구요.
이 때 props에 있는 value는 width 값을 퍼센티지 단위로써 받고 있습니다.

**Comment by 0214kbs** [comment]
넵 확인했습니다! 참고해서 수정하겠습니다
